name: push-tag-act
on:
  push:
    tags:
      - v*
env: 
  IMAGE_NAME: test
  IMAGE_TAG: 1.0
jobs:
  push-tag-act:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Hadolint
        uses: brpaz/hadolint-action@master
      - name: Docker Image Build
        run: |      
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker images -a
      # - name: Dockle
      #   uses: hands-lab/dockle-action@v1
      #   with:
      #     image: $IMAGE_NAME