name: push-tag-act
on:
  push:
    tags:
      - v*
jobs:
  push-tag-act:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set version
        id: version
        run: |
          REPOSITORY=$(echo ${{ github.repository }} | sed -e "s#.*/##")
          VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          echo ::set-output name=name::$REPOSITORY
          echo ::set-output name=version::$VERSION
      - name: Hadolint
        uses: brpaz/hadolint-action@master
      - name: Docker Image Build
        run: |      
          docker build -t ${{ steps.version.outputs.name }}:${{ steps.version.outputs.version }} .
          docker images -a
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ steps.version.outputs.name }}:${{ steps.version.outputs.version }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'